# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceec242612995c578e2cd948fd87312baa516c14550f6d03b42de9769c28605d0165c7f4279e40e4cad7a4c1378cc5eea30e645e2e4672ccd273916e001c0a1e

test:
  secret_key_base: f328f000315661c5767f183e148c861a947721681514d7bef40b8e2a608866845ba372f88b5072a361544f7f7ca0f42242fe766f5d074ae274262f9ec08b7185

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
