# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb25c5452feae90b6d2ca8ca0838a4945f2f398e8c4710fc2c1536a87de508eed6705be5996c039d13a9a3dbc4982ac8f65628eecad7a3417066081ebb435e05

test:
  secret_key_base: 6fab3b91da37e341d5ebeab7834e4ee0ceb5887c8fb69f177512d011852e7a13efd9e56bdade59853042c831e0e28561d7a674497534d788ed9be05599fa189c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
